theme: jekyll-theme-minimal
title: ["Formal Methods \n for the \n Informal Engineer"]
name: Formal Methods for the Informal Engineer
description: [March 19-20 at the Broad Institute of MIT and Harvard]
site.github.is_user_page: false
